name: Capture Webcams
on:
  workflow_dispatch:
jobs:
  capture_screenshots:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          npm install
          npm install puppeteer

      - name: Run main script
        env:
          AQI_API_KEY: ${{ secrets.AQI_API_KEY }}
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
          WINDY_API_KEY: ${{ secrets.WINDY_API_KEY }}
        run: npx tsx src/index.ts

      - name: Checkout output branch
        run: |
          git fetch
          git checkout output
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Copy and commit new screenshots
        run: |
          # Create screenshots directory if it doesn't exist
          mkdir -p screenshots

          # Copy new screenshots while preserving existing ones
          cp -n ../screenshots/* screenshots/ 2>/dev/null || true

          git add screenshots/
          git commit -m "Add webcam screenshots for $(date)" || echo "No changes to commit"
          git push origin output
