name: Capture Webcams

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  capture_screenshots:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: output

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          npm install
          npm install puppeteer

      - name: Run main script
        env:
          AQI_API_KEY: ${{ secrets.AQI_API_KEY }}
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
          WINDY_API_KEY: ${{ secrets.WINDY_API_KEY }}
        run: npx tsx src/index.ts

      - name: Commit and push screenshots
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git fetch
          git checkout -B output
          git pull origin output
          git add screenshots/
          git commit -m "Add webcam screenshots for $(date +%Y-%m-%d_%H-%M-%S)"
          git push origin output
