name: Cleanup and Process Image

on:
  workflow_run:
    workflows: ["Capture Webcams"]
    types:
      - completed
  workflow_dispatch: # Allows manual triggering

jobs:
  process_images:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: output

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install opencv-python scikit-learn

      - name: Run image processing script
        run: python cleanup/main.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git pull origin output
          git add cleanshots/
          git commit -m "Processed images for $(date +%Y-%m-%d_%H-%M-%S)"
          git push origin output
