name: Daily Cleanup and Image Processing

on:
  schedule:
    # Runs daily at midnight
    - cron: "0 0 * * *"
  workflow_dispatch: # Allows manual triggering

jobs:
  process_images:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install opencv-python scikit-learn

      # Step 4: Run the Python script
      - name: Run image processing script
        run: python path/to/your/script.py
