name: Cleanup and Process Image

on:
  workflow_run:
    workflows: ["Capture Webcams"]
    types:
      - completed
  workflow_dispatch: # Allows manual triggering

jobs:
  process_images:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install opencv-python scikit-learn

      # Step 4: Run the Python script
      - name: Run image processing script
        run: python cleanup/main.py

      # Step 5: Commit and push changes
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Daily update: Processed images and cleaned data"
          git pull --ff-only
          git push
