name: Capture Webcams and Process Images

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  capture_screenshots:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies for webcam capture
        run: |
          npm install
          npm install puppeteer

      - name: Run main script for webcam capture
        env:
          AQI_API_KEY: ${{ secrets.AQI_API_KEY }}
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
          WINDY_API_KEY: ${{ secrets.WINDY_API_KEY }}
        run: npx tsx src/index.ts

      - name: Commit and push screenshots to output branch
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git pull
          git checkout -B output
          git add screenshots/
          git commit -m "Add webcam screenshots for $(date)"
          git push origin output --force

  process_images:
    runs-on: ubuntu-latest
    needs: capture_screenshots

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: output

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies for image processing
        run: |
          python -m pip install --upgrade pip
          pip install opencv-python scikit-learn

      - name: Run image processing script
        run: python cleanup/main.py

      - name: Commit and push processed images to output branch
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git pull
          git add cleanshots/
          git commit -m "Processed images and cleaned data for $(date)"
          git push origin output --force
